Add python workflow
daiseeai/workflows pull request #3
Opened 2023-04-21 07:08 UTC by ConDai

Checks
1.  black formatting
2.  isort formatting 
3.  types (optional)
4. linting (optional)
5. testing (optional)

Type checking, linting and testing are optional for now as they do not all pass for every python repo. They are enabled by default but can be disabled by the following flags
- `typecheckMustPass`
- `lintingMustPass`
- `testsMustPass`

2023-04-21 07:11 UTC, jordyjwilliams commented
Another suggestion `pydocstyle`could be worth adding

2023-04-21 07:12 UTC, ryan-keswick approved these changes
Nice!

2023-04-21 07:14 UTC, ConDai commented
> Another suggestion `pydocstyle`could be worth adding

Will add `pydocstyle`

2023-04-21 07:16 UTC, jordyjwilliams commented
Sweet sounds good. I will review properly on Monday

2023-04-24 02:41 UTC, ConDai commented
Bump

2023-04-24 03:03 UTC, jordyjwilliams requested changes
Mostly thinking that a `python_version` matrix would be cool to allow for testing/validation against multiple versions.

Would also have an open question about the `.` root use for all static checks. Happy to have a larger discussion, but if the aim of this PR is to make a reusable boiler plate etc it could be worth having these directories configurable. For example in [this draft state](https://github.com/daiseeai/api-definitions/blob/b5e1a4f0a862a4323d224173c13c92bc8f099b76/audio-processing-api/poetry_utils.py#L30-L43) when more configuration to `pystest-coverage` was desired. It could also be worth adding/uploading the coverage.


The examples here: https://github.com/marketplace/actions/install-poetry-action#testing-using-a-matrix are quite nice... I don't think the action is necessary for us here. But we could use the `caching` as we don't currently check for this. Additionally, a `code-coverage` upload could be nice.

2023-04-24 03:08 UTC, jordyjwilliams commented on .github/workflows/python.yaml
> +          pip install poetry
Actually as defined [here](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages) I would vote for modelling that flow.

2023-04-24 03:08 UTC, jordyjwilliams commented on .github/workflows/python.yaml
> +        uses: actions/setup-python@v3
```suggestion
        uses: actions/setup-python@v4
```

2023-04-24 03:13 UTC, ryan-keswick commented
The great thing about these workflows, is that the user can define what version they want to use. Based on the commit hash, so upstream changes here won't break the CICD in lots of repos. So I'd advocate for getting this out and finding what works and what doesn't

2023-04-24 03:15 UTC, jordyjwilliams commented
ahh in that case yeah, I don't want to be a blocker here. Happy to make some suggestions in a PR at a later date. LGTM

2023-04-24 03:15 UTC, jordyjwilliams approved these changes

2023-04-24 03:16 UTC, ConDai commented on .github/workflows/python.yaml
> +        type: boolean
I don't follow. What's style ghaction? Also don't understand the code above? Is that a gh action? If so what's `md`?

2023-04-24 03:17 UTC, jordyjwilliams commented on .github/workflows/python.yaml
> +        type: boolean
nvm  it was more a consideration with why this wouldn't run on `on: [push]`. But then I realized this was a work flow definition. I meant to delete this comment.

2023-04-24 03:18 UTC, merged

2023-04-24 03:19 UTC, ConDai commented
I'll create an issue so I don't forget the suggestions

2023-04-24 03:20 UTC, jordyjwilliams commented
> I'll create an issue so I don't forget the suggestions

sgtm, I can potentially have a look at it this week and add in a quick few adjustments, but yeah for sure see benefit in getting this implemented and to use this in the current state.

2023-04-24 03:23 UTC, jack-davies commented
We should probably keep `Request Changes` reviews for major issues that ought to block a PR until resolved, as they prevent merging-

> Submit feedback that must be addressed before merging.

2023-04-24 03:29 UTC, jordyjwilliams commented
@jack-davies yeah my bad I guess I had used this rather informally/incorrectly in the past as more of a  hey  "x or y could be implemented or easily improved here". Sorry for my incorrect usage of `must` keyword :P

2023-04-24 04:19 UTC, ConDai commented
[RFC 2119](https://www.rfc-editor.org/rfc/rfc2119) :smile: